[package]
name = "pulsar-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3"
pulsar = "5.1"
tokio = { version = "1", features = ["full"] }
uuid = "1.15.1"
