version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: ["bin/pulsar", "standalone"]
    ports:
      - "6650:6650"  # Pulsar binary protocol
      - "8080:8080"  # Pulsar REST admin interface